-- ============================================================================
-- NZ Election Tracker — Seed: NZ Electorates (2024 boundaries, 72 total)
-- GeoJSON and demographics to be loaded separately
-- ============================================================================

-- General Electorates (65)
INSERT INTO electorates (name, electorate_type, region) VALUES
  ('Auckland Central',        'general', 'Auckland'),
  ('Banks Peninsula',         'general', 'Canterbury'),
  ('Bay of Plenty',           'general', 'Bay of Plenty'),
  ('Botany',                  'general', 'Auckland'),
  ('Christchurch Central',    'general', 'Canterbury'),
  ('Christchurch East',       'general', 'Canterbury'),
  ('Coromandel',              'general', 'Waikato'),
  ('Dunedin',                 'general', 'Otago'),
  ('East Coast',              'general', 'Gisborne'),
  ('Epsom',                   'general', 'Auckland'),
  ('Hamilton East',           'general', 'Waikato'),
  ('Hamilton West',           'general', 'Waikato'),
  ('Hutt South',              'general', 'Wellington'),
  ('Ilam',                    'general', 'Canterbury'),
  ('Invercargill',            'general', 'Southland'),
  ('Kaikōura',               'general', 'Canterbury'),
  ('Kaipara ki Mahurangi',   'general', 'Auckland'),
  ('Kelston',                 'general', 'Auckland'),
  ('Mana',                    'general', 'Wellington'),
  ('Māngere',                'general', 'Auckland'),
  ('Manurewa',                'general', 'Auckland'),
  ('Maungakiekie',            'general', 'Auckland'),
  ('Mt Albert',               'general', 'Auckland'),
  ('Mt Roskill',              'general', 'Auckland'),
  ('Napier',                  'general', 'Hawkes Bay'),
  ('Nelson',                  'general', 'Nelson'),
  ('New Lynn',                'general', 'Auckland'),
  ('New Plymouth',            'general', 'Taranaki'),
  ('North Shore',             'general', 'Auckland'),
  ('Northcote',               'general', 'Auckland'),
  ('Northland',               'general', 'Northland'),
  ('Ōhāriu',                'general', 'Wellington'),
  ('Ōtaki',                  'general', 'Manawatū'),
  ('Pakuranga',               'general', 'Auckland'),
  ('Palmerston North',        'general', 'Manawatū'),
  ('Panmure-Ōtāhuhu',       'general', 'Auckland'),
  ('Papakura',                'general', 'Auckland'),
  ('Port Waikato',            'general', 'Waikato'),
  ('Rangitata',               'general', 'Canterbury'),
  ('Rangitīkei',             'general', 'Manawatū'),
  ('Remutaka',                'general', 'Wellington'),
  ('Rongotai',                'general', 'Wellington'),
  ('Rotorua',                 'general', 'Bay of Plenty'),
  ('Selwyn',                  'general', 'Canterbury'),
  ('Southland',               'general', 'Southland'),
  ('Taieri',                  'general', 'Otago'),
  ('Takanini',                'general', 'Auckland'),
  ('Tamaki',                  'general', 'Auckland'),
  ('Taranaki-King Country',   'general', 'Taranaki'),
  ('Tauranga',                'general', 'Bay of Plenty'),
  ('Te Atatū',               'general', 'Auckland'),
  ('Tukituki',                'general', 'Hawkes Bay'),
  ('Upper Harbour',           'general', 'Auckland'),
  ('Waikato',                 'general', 'Waikato'),
  ('Waimakariri',             'general', 'Canterbury'),
  ('Wairarapa',               'general', 'Wellington'),
  ('Waitākere',              'general', 'Auckland'),
  ('Wellington Central',      'general', 'Wellington'),
  ('West Coast-Tasman',       'general', 'West Coast'),
  ('Whanganui',               'general', 'Manawatū'),
  ('Whangārei',              'general', 'Northland'),
  ('Whangaparāoa',           'general', 'Auckland'),
  ('Wigram',                  'general', 'Canterbury'),
  ('Flat Bush',               'general', 'Auckland'),
  ('Taupō',                  'general', 'Waikato')
ON CONFLICT (name) DO NOTHING;

-- Māori Electorates (7)
INSERT INTO electorates (name, electorate_type, region) VALUES
  ('Hauraki-Waikato',         'maori', 'Waikato'),
  ('Ikaroa-Rāwhiti',         'maori', 'East Coast'),
  ('Tāmaki Makaurau',        'maori', 'Auckland'),
  ('Te Tai Hauāuru',         'maori', 'Manawatū'),
  ('Te Tai Tokerau',          'maori', 'Northland'),
  ('Te Tai Tonga',            'maori', 'South Island'),
  ('Waiariki',                'maori', 'Bay of Plenty')
ON CONFLICT (name) DO NOTHING;
